### ISSUE TITLE
Такое сложно будет тестировать

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week4HomeworkHouseService#5]
https://github.com/AlekseiILitvinov/Week4HomeworkHouseService/blob/6d21fe051d9adaaf08da8a3307c611744381c67d/src/main/java/ru/itpark/HouseService.java#L63-L67

**Comment by coursar** [comment]
И модифицировать тоже

**Comment by AlekseiILitvinov** [comment]
Да, понимаю. Просто пытался сымитировать комплексный поиск, как на ЦИАН. Переделаю через отдельные небольшие методы. А на самом деле, как там следует сделать? Через comparable?

**Comment by coursar** [comment]
Нет, `Comparable` для сортировки. Если через цикл, то пользуйтесь простыми условиями (переворачивайте логику с подходит на не подходит) и `continue`:

```java
if (!parameters.getDistrict().toLowerCase().contains(house.getDistrict().toLowerCase())) {
  continue;
}

if (другое условие) {
  continue;
}

// в самом конце, если все проверки прошли:
result.add(house);
```

Можно тело цикла вынести в отдельный метод и использовать early exit
